### ISSUE TITLE
Ref for "testing is not a panacea"

### ISSUE THREAD

**Issue by dfalster** [dfalster/plant_blogpost#1]
Hi @richfitz,
Did you have a link for the phrase "testing is not a panacea"? A quick search revealed this possibility http://philmcminn.staff.shef.ac.uk/publications/tr3.pdf

**Comment by richfitz** [comment]
I'm not able to find the thing I was thinking of, but one of:

- http://blog.caplin.com/2012/05/08/why-100-code-coverage-is-not-enough/
- http://designcoderelease.blogspot.co.uk/2011/06/100-coverage-is-not-enough.html
- http://www.codeproject.com/Articles/228859/Coverage-is-not-enough
